name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create resources folder
        run: mkdir -p ./src/main/resources

      - name: Create application.properties
        run: touch ./src/main/resources/application.properties

      - name: Setup application.properties
        run: echo "${{secrets.APPLICATION}}" > ./src/main/resources/application.properties

      - name: Check application.properties
        run: cat ./src/main/resources/application.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push - dev
        uses: docker/build-push-action@v4
        if: contains(github.ref, 'develop')
        with:
          context: .
          file: ./Dockerfile.dev
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:dev

      - name: Build and push - prod
          uses: docker/build-push-action@v4
          if: contains(github.ref, 'main')
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:prod
