name: Java CI with Gradle

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create resources folder
        run: mkdir -p ./src/main/resources

      - name: Create application.properties
        run: touch ./src/main/resources/application.properties

      - name: Setup application.properties
        run: echo "${{secrets.APPLICATION}}" > ./src/main/resources/application.properties

      - name: Check application.properties
        run: cat ./src/main/resources/application.properties

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build
